apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-zeppelin
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/electinfo/spark-on-kubernetes
    targetRevision: main
    path: manifests/zeppelin/base
  destination:
    server: https://kubernetes.default.svc
    namespace: zeppelin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
