apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-images-build
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/electinfo/spark-on-kubernetes.git'
    path: 'tasks'
    targetRevision: main
  destination:
    namespace: tekton-pipelines
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true