---
# Spark images webhook at spark.webhook.elect.info
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: spark-images-webhook
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`spark.webhook.elect.info`)
      kind: Rule
      services:
        - name: el-spark-images-listener
          namespace: tekton-pipelines
          port: 8080
  tls:
    secretName: spark-webhook-electinfo-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: spark-webhook-electinfo-tls
  namespace: traefik
spec:
  commonName: spark.webhook.elect.info
  dnsNames:
    - spark.webhook.elect.info
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: spark-webhook-electinfo-tls