apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pipeline.yaml
  - triggers.yaml
  - ingress-routes.yaml
  # pipelinerun.yaml uses generateName, use: kubectl create -f pipelinerun.yaml