apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: app-zeppelin

resources:
  - namespace.yaml
  - vault-auth.yaml
  - vault-static-secret.yaml
  - configmap.yaml
  - rbac.yaml
  - pvc.yaml
  - spark-checkpoint-pv.yaml
  - deployment.yaml
  - service.yaml
  - ingress-route.yaml
  - ../../../config  # ConfigMaps from config files
