apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: zeppelin-github-deploy-key
  namespace: zeppelin
spec:
  type: kv-v2
  mount: electinfo
  path: app-zeppelin/github
  destination:
    name: zeppelin-github-secret
    create: true
  refreshAfter: 1h
  vaultAuthRef: zeppelin-vault-auth
