apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-spark-history-server
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/electinfo/spark-on-kubernetes.git'
    path: 'manifests/spark-history-server/base'
    targetRevision: main
  destination:
    namespace: spark
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true