apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Generate ConfigMaps from config files
# Referenced by: manifests/zeppelin/base/kustomization.yaml

namespace: zeppelin

configMapGenerator:
  - name: spark-conf
    files:
      - core-site.xml
      - spark-defaults.conf
      - executor-pod-template.yaml
  - name: zeppelin-interpreter-spec
    files:
      - 100-interpreter-spec.yaml
  - name: zeppelin-interpreter-setting
    files:
      - interpreter-setting.json

generatorOptions:
  disableNameSuffixHash: true
